export const positionLabels = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Administrator",
  SALES: "Sales",
  EVENT_MANAGER: "Event Manager",
  FINANCE: "Finance",
  STAFF: "Staff",
};

export const skillsByPosition = {
  SUPER_ADMIN: [
    "System Administration",
    "User Management",
    "Role & Permission Management",
    "System Configuration",
    "Security Management",
    "Data Management",
    "Audit & Compliance",
    "Reporting",
  ],
  ADMIN: [
    "User Management",
    "Workspace Management",
    "CRM Management",
    "Sales Administration",
    "Operations Management",
    "Finance Administration",
    "Reporting",
  ],
  SALES: [
    "Lead Management",
    "Customer Communication",
    "CRM",
    "Sales Pipeline",
    "Proposal Preparation",
    "Negotiation",
    "Quotation",
    "Contract Management",
  ],
  EVENT_MANAGER: [
    "Event Planning",
    "Project Management",
    "Task Management",
    "Team Coordination",
    "Vendor Management",
    "Budget Planning",
    "Client Communication",
    "Risk Management",
    "On-site Operations",
  ],
  FINANCE: [
    "Budget Management",
    "Cost Estimation",
    "Quotation Review",
    "Invoice Management",
    "Payment Tracking",
    "Expense Management",
    "Financial Reporting",
    "Budget Approval",
  ],
  STAFF: [
    "Task Execution",
    "Event Setup",
    "Logistics Support",
    "Equipment Handling",
    "On-site Support",
    "Progress Reporting",
    "Team Collaboration",
  ],
};
